### ISSUE TITLE
not working on default ubuntu 16.10 install

### ISSUE THREAD

**Issue by niedakh** [cuth/unsplash-wallpaper#16]
```
niedakh@niedakh-Latitude-E6520:~$ unsplash-wallpaper 
/usr/local/lib/node_modules/unsplash-wallpaper/cli.js:6
const { boolOptions, minimistAliases, triggerDownload } = require('./lib/args');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
niedakh@niedakh-Latitude-E6520:~$
```

**Comment by cuth** [comment]
Ah, looks like it comes with a pretty old version of Node. Could you try upgrading?
